vich_uploader:
    db_driver: orm

    mappings:
        suivi_documents:
            uri_prefix: /uploads/suivis
            upload_destination: '%kernel.project_dir%/public/uploads/suivis'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
